#!/bin/bash
COMMAND=$(cat /root/.bash_history | grep "^kubectl delete -f" | wc -l)
if [ $COMMAND -eq 0 ]; then
  echo "FAIL: The kubectl delete definition command was not run."
  exit 1
fi

POD=$(kubectl get pod nginx --output json)
# Check if we have a result
if [ $? == 0 ]; then
  echo "FAIL: The pod named nginx was not removed. Hint: check if its still terminating with kubectl get pods"
  exit 1
fi

exit 0
