#!/bin/bash
POD=$(kubectl get pod nginx --output json)
# Check if we have a result
if [ $? == 1 ]; then
  echo "FAIL: There was no pod called nginx"
  exit 1
fi

CONTAINERS=$(echo $POD | jq -r '.spec.containers | length')
if [ $CONTAINERS != 2 ]; then
  echo "FAIL: Expected 2 containers in pod nginx: found $CONTAINERS"
  exit 1
fi

exit 0
