#!/bin/bash
cat > /root/nginx.yml <<EOF
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.12-alpine
    ports:
    - containerPort: 80
EOF

# Create a watcher for the yaml file.
DIRECTORY_TO_WATCH="/root/nginx.yml"
RESULT_FILE="/tmp/nginx-yml-touched"

inotifywait -d -o ${RESULT_FILE} -e access -r ${DIRECTORY_TO_WATCH}
